services:

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_api
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  adminer:
    image: adminer
    ports:
      - "8000:8080"
    depends_on:
      - database

  api:
    image: node:22.14
    volumes:
      - ".:/app"
    working_dir: /app
    ports:
      - "3000:3000"
      - "5555:5555"
    command: npm run dev
    depends_on:
      - database

volumes:
  pgdata:
